extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    - 2
    - always
    - [feat, fix, refactor, test, docs, chore, perf, style, ci]
  subject-case:
    - 2
    - always
    - lower-case
