"""Markdown report generator."""

from __future__ import annotations

from ..models import Assessment, CategoryResult, CheckResult


def render_markdown(assessment: Assessment) -> str:
    """Render a full assessment as a Markdown report."""
    lines: list[str] = []
    _header(lines, assessment)
    _summary_table(lines, assessment)

    for category in assessment.categories:
        _category_section(lines, category)

    _references(lines, assessment)
    return "\n".join(lines)


def _header(lines: list[str], assessment: Assessment) -> None:
    lines.append(f"# AI Harness Scorecard: {assessment.repo_name}")
    lines.append("")
    lines.append(
        f"**Grade: {assessment.grade.value}** ({assessment.overall_score:.1f}/100) "
        f"| {assessment.grade_description}"
    )
    lines.append("")
    lines.append(f"- **Repository**: `{assessment.repo_path}`")
    lines.append(
        f"- **Languages**: {', '.join(assessment.languages) if assessment.languages else 'none detected'}"
    )
    lines.append(f"- **Assessed**: {assessment.timestamp:%Y-%m-%d %H:%M UTC}")
    lines.append(f"- **Checks**: {assessment.passed_checks}/{assessment.total_checks} passed")
    lines.append("")


def _summary_table(lines: list[str], assessment: Assessment) -> None:
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Weight | Score | Checks |")
    lines.append("|----------|--------|-------|--------|")
    for cat in assessment.categories:
        passed = sum(1 for c in cat.checks if c.passed)
        total = len(cat.checks)
        bar = _progress_bar(cat.percentage)
        lines.append(
            f"| {cat.name} | {cat.weight:.0%} | {cat.percentage:.0f}% {bar} | {passed}/{total} |"
        )
    lines.append("")


def _category_section(lines: list[str], category: CategoryResult) -> None:
    lines.append(f"## {category.name} ({category.percentage:.0f}%)")
    lines.append("")

    for check in category.checks:
        _check_item(lines, check)

    lines.append("")


def _check_item(lines: list[str], check: CheckResult) -> None:
    icon = "PASS" if check.passed else "FAIL"
    score_text = f"{check.score:.0f}/{check.max_points:.0f}"
    lines.append(f"### [{icon}] {check.name} ({score_text})")
    lines.append("")
    lines.append(f"_{check.source}_")
    lines.append("")
    lines.append(f"**Evidence**: {check.evidence}")
    if check.remediation:
        lines.append("")
        lines.append(f"**Remediation**: {check.remediation}")
    lines.append("")


def _references(lines: list[str], assessment: Assessment) -> None:
    sources: set[str] = set()
    for cat in assessment.categories:
        for check in cat.checks:
            sources.add(check.source)

    lines.append("## References")
    lines.append("")
    for source in sorted(sources):
        lines.append(f"- {source}")
    lines.append("")
    lines.append("---")
    lines.append(
        "*Generated by [ai-harness-scorecard]"
        "(https://github.com/markmishaev/ai-harness-scorecard)*"
    )


def _progress_bar(percentage: float, width: int = 10) -> str:
    filled = round(percentage / 100 * width)
    empty = width - filled
    return "[" + "#" * filled + "-" * empty + "]"
